### ISSUE TITLE
关于量化的理论请教

### ISSUE THREAD

**Issue by www516717402** [ArtyZe/yolo_quantization#7]
感谢开源！
1. 量化之后的参数如何进行前向推理的转化，如何转化为onnx、ncnn等进行推理。
2. 网络层量化较为容易，后处理部分如何量化？

**Comment by ArtyZe** [comment]
1. 我这版量化后，参数文件里有量化的scale和zeropoint等，需要在转onnx或者ncnn解析过程中添加代码，才能转化
2. 你说的yolo层？即使是目前所有的量化方式，后处理都是浮点做的，因为后处理是随时在变的，即使darknet的yolo层也是改了又改，没必要用定点去做，如果确实有必要，需要单独写


| |
高扬
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年10月13日 ***@***.***> 写道：

感谢开源！

量化之后的参数如何进行前向推理的转化，如何转化为onnx、ncnn等进行推理。
网络层量化较为容易，后处理部分如何量化？

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by www516717402** [comment]
@ArtyZe 感谢回复！关于第二点明白了，关于第一点，获得的额外参数scale和zeropoint在onnx中如何表示呢？转换完成之后，onnx有专门针对量化的inference的load方法吗？

**Comment by ArtyZe** [comment]
当然没有，第一种就是自己去改onnx的前向代码，第二种就是我认为可以把scale和zeropoint放在onnx相关算子的输入中，或者quantlinear算子中


| |
高扬
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年10月14日 ***@***.***> 写道：
1. 我这版量化后，参数文件里有量化的scale和zeropoint等，需要在转onnx或者ncnn解析过程中添加代码，才能转化
2. 你说的yolo层？即使是目前所有的量化方式，后处理都是浮点做的，因为后处理是随时在变的，即使darknet的yolo层也是改了又改，没必要用定点去做，如果确实有必要，需要单独写


| |
高扬
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年10月13日 ***@***.***> 写道：

感谢开源！

量化之后的参数如何进行前向推理的转化，如何转化为onnx、ncnn等进行推理。
网络层量化较为容易，后处理部分如何量化？

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by www516717402** [comment]
@ArtyZe 第一种太麻烦了，第二种可行。感谢解惑！
